  ###### STOP PROTEUS-JOB ######
---
- hosts: treelogic:&master
  remote_user: root
  tasks:
    - name: get flink running jobs
      uri:
        url: http://clusteridi.master.treelogic.local:8081/jobs
        method: GET
        return_content: yes
      register: job_list
      ignore_errors: yes

    - name: get proteus-job id
      set_fact:
        job_id: "{{ job_list.json['jobs-running'][0] }}"
      when: job_list.failed == False

    - name: stop proteus-job
      shell: "./flink cancel {{ job_id }}"
      args:
        chdir: /home/proteususer/proteus-engine/build-target/bin/
      when: job_id is defined

    - name: debug
      debug:
        msg: " Cant stop the proteus_job: {{ job_list.msg }}"
      when: job_list.failed
