###### STOP PROTEUS_PRODUCER -> slave02 ######
---
- hosts: treelogic:&slave02
  remote_user: root
  tasks:
    - name: get running proteus_producer task
      shell: "jps | grep Launcher | awk '{print $1}'"
      register: proteus_producer

    - name: setting producer_pid
      set_fact:
        proteus_producer_pid: "{{ proteus_producer.stdout_lines[0] }}"
      when: proteus_producer.stdout_lines|length > 0

    - name: kill proteus_producer
      shell: "kill -9 {{ proteus_producer_pid }}"
      when: proteus_producer.stdout_lines|length > 0
